language: node_js

node_js:
  - stable

before_script: chmod 0777 ./node_modules/.bin/mocha

install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

after_script:
  - npm run coverage